export const INIT_APP = 'INIT_APP';
export const INIT_APP_SUCCESS = 'INIT_APP_SUCCESS';
export const INIT_APP_ERROR = 'INIT_APP_ERROR';

export const SET_SORT_DATE = 'SET_SORT_DATE';
export const SET_GROUPS = 'SET_GROUPS';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_TRANS_WITHOUT_GROUPS = 'SET_TRANS_WITHOUT_GROUPS';
export const NORMALIZE_GROUPS_TRANS = 'NORMALIZE_GROUPS_TRANS';
export const PARSE_TRANSACTIONS = 'PARSE_TRANSACTIONS';
